"use client";

import { CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { Analytics, AnalyticsRow } from "@/lib/types";

const colors = ["#275c48", "#ef744c", "#d2a842", "#69a694", "#6c7c55", "#8f6852"];
const tooltipStyle = { borderRadius: "12px", border: "1px solid #d9d5c9", background: "#fffdf8", boxShadow: "0 8px 20px rgba(41,56,43,.08)" };
function EmptyChart({ title }: { title: string }) { return <section className="paper-card p-5"><h2 className="text-xl font-bold">{title}</h2><p className="mt-12 text-center text-sm text-stone-500">No click data yet.</p></section>; }
function Breakdown({ title, data }: { title: string; data: AnalyticsRow[] }) { if (!data.length) return <EmptyChart title={title} />; return <section className="paper-card p-5"><h2 className="text-xl font-bold">{title}</h2><div className="mt-4 h-64"><ResponsiveContainer><PieChart><Pie data={data} dataKey="clicks" nameKey="label" outerRadius={85} stroke="#fffdf8" strokeWidth={3}>{data.map((item, index) => <Cell key={item.label} fill={colors[index % colors.length]} />)}</Pie><Tooltip contentStyle={tooltipStyle} /><Legend /></PieChart></ResponsiveContainer></div></section>; }
export function AnalyticsCharts({ analytics }: { analytics: Analytics }) { return <><section className="paper-card p-5 sm:p-6"><p className="eyebrow">Activity</p><h2 className="mt-1 text-2xl font-bold">Clicks over time</h2>{analytics.perDay.length ? <div className="mt-5 h-72"><ResponsiveContainer><LineChart data={analytics.perDay}><CartesianGrid stroke="#e7e2d8" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#78716c", fontSize: 12 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#78716c", fontSize: 12 }} /><Tooltip contentStyle={tooltipStyle} /><Line type="monotone" dataKey="clicks" stroke="#275c48" strokeWidth={3} dot={{ r: 3, fill: "#ef744c", strokeWidth: 0 }} activeDot={{ r: 6 }} /></LineChart></ResponsiveContainer></div> : <p className="mt-12 text-center text-sm text-stone-500">No click data yet.</p>}</section><div className="mt-5 grid gap-5 md:grid-cols-2"><Breakdown title="Countries" data={analytics.country} /><Breakdown title="Devices" data={analytics.device} /><Breakdown title="Browsers" data={analytics.browser} /><Breakdown title="Referrers" data={analytics.referrer} /></div></>; }
